### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by matty111** [concentricsky/badgr-ui#101]
is there a dockerfile?

**Comment by ottonomy** [comment]
Not yet, but feel free to contribute one if it is useful for your efforts. As this is a static javascript/css/html application, there is little server-side processing that needs to be done, so implementers often choose to deploy via AWS S3/Cloudfront or similar services for static assets.

**Comment by matty111** [comment]
Thank you for the answer.
Can be a simple question, but do you know open source services like these?
