### ISSUE TITLE
no npm run build:prod exists but is documented

### ISSUE THREAD

**Issue by niccokunzmann** [concentricsky/badgr-ui#49]
There is no `npm run build:prod` as described here:

- https://badgr.org/hosts/#badgr-ui-prod
- https://github.com/concentricsky/badgr-ui#building

Code:

https://github.com/concentricsky/badgr-ui/blob/48ad3201461cd60f67dcafe64a6c068ee114eb07/package.json#L12

**Comment by niccokunzmann** [comment]
I was using `npm run-script ng build` and it seems to build the website correctly.
I see these options for solving this:

- document `npm run-script ng build`
- create build:prod with `npm run-script ng build`
- create a new command and document that

What do you people with more experience in the project think?

**Comment by nqthqn** [comment]
@niccokunzmann I've updated the README in `release/bob` branch.

**Comment by niccokunzmann** [comment]
I would not close this until this is in develop because develop is the branch people look at and do not search the other many branches.
