### ISSUE TITLE
no npm run server but documented

### ISSUE THREAD

**Issue by niccokunzmann** [concentricsky/badgr-ui#50]
https://github.com/concentricsky/badgr-ui#run-project-in-your-browser
documents that one would run npm run server to run the server.
This does not work for me.

```
$ npm run server
npm ERR! missing script: server

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-03-11T22_45_45_051Z-debug.log

```

It is absent in the package.json file.

**Comment by niccokunzmann** [comment]
I would not close this until this is in develop because develop is the branch people look at and do not search the other many branches. 

a8199e1

**Comment by nqthqn** [comment]
https://github.com/concentricsky/badgr-ui#run-project-in-your-browser
