### ISSUE TITLE
Describe the workflow

### ISSUE THREAD

**Issue by niccokunzmann** [concentricsky/badgr-ui#52]
In #51, @nqthqn created a commit and closed the pull request. This commit is in the relaese/bob branch.
I am used to create pull requests to the default branch, in this case develop. If the commit fixing the issue is in this branch, the issue is closed. From this branch on the commit wanders into releases etc. 

What is your process in this case? If I contribute, which branch do I contribute to?
Why are there more commits in release/bob than in develop?

Readable: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia

I would like to close this if the answer is in the README.md file of the default branch.

**Comment by ottonomy** [comment]
Thanks, @niccokunzmann. `develop` is indeed the default branch, and we follow a Git Flow type workflow where `master` is the stable branch, `develop` is the active development branches, and we typically have feature branches diverge from `develop` and PR back into `develop`. Then we branch release branches off of develop. At the moment, there is both work toward a release (codenamed "Bob Badgr") and a future release "Charlie Badgr". Charlie hasn't yet diverged from develop, but Bob has, and to facilitate work on both, letting us split features improvements into their scheduled releases, coordinated on both badgr-server and badgr-ui repositories. `release/bob` will be merged back into `develop` periodically. This isn't ideal or pure Git Flow. We'll be focusing on working on fewer more discrete things at once, which lets us use the release branches less.

Thanks for your Pull Request! It was 100% correct, just so happens we worked in parallel and Let me know if you have any more questions.

**Comment by niccokunzmann** [comment]
@ottonomy Thanks for the answer. This clarifies it. I would ask: is it ok to put such information into the README file as it is important to know if you contribute?
