### ISSUE TITLE
Problem with "npm start" : error ts2304 Cannot find name 'ShareSocialDialogVersionOption'

### ISSUE THREAD

**Issue by 6tine** [concentricsky/badgr-ui#60]
Hi,
I followed the tutorial to install badgr-ui, but when I'm trying to run "npm start" or "npm run start", there is this error I can't resolve : 

**ERROR in src/app/common/dialogs/share-social-dialog/share-social-dialog.component.ts(40,19): error TS2304: Cannot find name 'ShareSocialDialogVersionOption'. Failed to compile.**

I'v tried many things but without success... "npm install" run well, I have just 2 warnings but I don't think it's the cause of the problem.

![capture_erreur_npm_start](https://user-images.githubusercontent.com/34345329/56965433-9821e700-6b5d-11e9-840e-e9a2a7738e66.PNG)

Does anyone know how to solve this problem? Thank you for your help.

**Comment by nqthqn** [comment]
@6tine Fixed.
