### ISSUE TITLE
Issue in building badgr-ui for `build:prod`

### ISSUE THREAD

**Issue by rajiff** [concentricsky/badgr-ui#8]
I am running this on latest MAC OS

`$ node --version
v9.5.0`

`$ npm --version
6.0.0`

The `build:prod` command is throwing bunch of errors and failing with exit code `2`

Can't figure out any thing from the log , can we please check and resolve and provide appropriate instructions

ERROR in badgr-ui/src/app/common/services/message.service.ts (30,45): Type 'UpdatableSubject<FlashMessage>' is not assignable to type 'Observable<FlashMessage>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<FlashMessage>' but public in type 'Observable<FlashMessage>'.

ERROR in badgr-ui/src/app/common/util/updatable-subject.ts (11,14): Class 'UpdatableSubject<T>' incorrectly extends base class 'Subject<T>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<T>' but public in type 'Subject<T>'.

ERROR in badgr-ui/src/app/common/model/managed-entity-set.ts (35,3): The 'this' context of type 'UpdatableSubject<EntitySetUpdate<EntityType, this>>' is not assignable to method's 'this' of type 'Observable<EntitySetUpdate<EntityType, this>>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<EntitySetUpdate<EntityType, this>>' but public in type 'Observable<EntitySetUpdate<EntityType, this>>'.

ERROR in badgr-ui/src/app/common/model/managed-entity.ts (23,53): The 'this' context of type 'UpdatableSubject<this>' is not assignable to method's 'this' of type 'Observable<this>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<this>' but public in type 'Observable<this>'.

ERROR in badgr-ui/src/app/common/model/linked-entity-set.ts (33,3): The 'this' context of type 'UpdatableSubject<EntitySetUpdate<EntityType, this>>' is not assignable to method's 'this' of type 'Observable<EntitySetUpdate<EntityType, this>>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<EntitySetUpdate<EntityType, this>>' but public in type 'Observable<EntitySetUpdate<EntityType, this>>'.

ERROR in badgr-ui/src/app/common/model/entity-set.ts (84,67): Type 'UpdatableSubject<{ [groupId: string]: EntityType[]; }>' is not assignable to type 'Observable<{ [groupId: string]: EntityType[]; }>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<{ [groupId: string]: EntityType[]; }>' but public in type 'Observable<{ [groupId: string]: EntityType[]; }>'.

ERROR in badgr-ui/src/app/common/model/entity-set.ts (85,77): The 'this' context of type 'UpdatableSubject<{ [groupId: string]: EntityType[]; }>' is not assignable to method's 'this' of type 'Observable<{ [groupId: string]: EntityType[]; }>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<{ [groupId: string]: EntityType[]; }>' but public in type 'Observable<{ [groupId: string]: EntityType[]; }>'.

ERROR in badgr-ui/src/app/common/model/entity-set.ts (128,63): Type 'UpdatableSubject<{ [mapId: string]: EntityType; }>' is not assignable to type 'Observable<{ [mapId: string]: EntityType; }>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<{ [mapId: string]: EntityType; }>' but public in type 'Observable<{ [mapId: string]: EntityType; }>'.

ERROR in badgr-ui/src/app/common/model/entity-set.ts (129,73): The 'this' context of type 'UpdatableSubject<{ [mapId: string]: EntityType; }>' is not assignable to method's 'this' of type 'Observable<{ [mapId: string]: EntityType; }>'.
  Property '_subscribe' is protected in type 'UpdatableSubject<{ [mapId: string]: EntityType; }>' but public in type 'Observable<{ [mapId: string]: EntityType; }>'.

ERROR in badgr-ui/node_modules/@types/webpack/index.d.ts (544,28): Type 'typeof "badgr-ui/node_modules/@types/tapable/index"' is not a constructor function type.

ERROR in badgr-ui/node_modules/@types/webpack/index.d.ts (586,46): Namespace '"badgr-ui/node_modules/@types/tapable/index"' has no exported member 'Plugin'.

**Comment by nqthqn** [comment]
What version of Typescript are you using?

**Comment by rajiff** [comment]
Whatever is in the package.json

Regards
Basavaraj

**Comment by ottonomy** [comment]
@rajiff thanks for the report. I have just successfully run `npm run build:prod` using a fresh node 9.5.0 nvm 6.0.0 environment created with nvm on MacOS 10.13.3. (The only delta between this and your setup is the one-step-behind OS, and potentially nvm). Are you using [nvm](https://github.com/creationix/nvm) (or something similar, -- I've just heard of [nodenv](https://github.com/nodenv/nodenv) for instance)?

**Comment by rajiff** [comment]
I am not using nvm or any other equivalent

I cloned once again from master branch and tried building, this time is has built

Will check again and reopen the issue if needed

**Comment by ottonomy** [comment]
Glad to hear, @rajiff. Cheers.

**Comment by mreyk** [comment]
It happened to me the same. I am not using nvm as I'm running this repo on Ubuntu 16.04 server.
```
nodejs -v
v4.2.6
```
```
npm -v
3.5.2
```
```
node -v
v10.8.0
```
Trying out badgr-ui v2.16.0
According to package.json:
```
    "typescript": "2.5.3",
```
